spring:
  application:
    name: spring-boot-ftp-integration

server:
  port: 8080

logging:
  level:
    root: DEBUG

configuration:
  sftp:
    file:
      sources:
        local: share/request
        remote: share/response
      filter: '*.txt'
    outbound:
      username: admin
      password: admin
      port: 22
      host: localhost
    inbound:
      username: admin
      password: admin
      port: 22
      host: localhost
